#!/bin/bash
#
# rpmsavenew — inspect and triage .rpmsave/.rpmnew files left by rpm updates
#
# Copyright (C) 2026 Red Hat, Inc.
# Copyright (C) 2026 Masatake YAMATO
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
declare _ACTION=

declare -ra actions=(
	help
	list-files
	diff
	sha1
	ls-lZ
	archive
	confspec
	# accept-rpmnew
	# remove-rpmnew
	# use-rpmsave
	# ask-AI
)

#
# common helpers
#
member()
{
	local elt=$1
	shift

	local e
	for e in "$@"; do
		if [[ "$e" == "$elt" ]]; then
			return 0
		fi
	done

	return 1
}

error()
{
	if [[ -n "$_ACTION" ]]; then
		echo -n "ERROR[$_ACTION]: "
	else
		echo -n "ERROR: "
	fi

	if [[ $# == 0 ]]; then
		echo "$1"
	else
		printf "$@"
		echo
	fi

	exit 1
} 1>&2

warning()
{
	if [[ -n "$_ACTION" ]]; then
		echo -n "warning[$_ACTION]: "
	else
		echo -n "warning: "
	fi

	if [[ $# == 0 ]]; then
		echo "$1"
	else
		printf "$@"
		echo
	fi
}

error_if_unknown_action()
{
	local a=$1

	if ! member "$a" "${actions[@]}"; then
		error "unknown action: $a"
	fi
}

options()
{
	echo
	echo "Options:"
}

examples()
{
	echo
	echo "Examples:"
}

print_option()
{
	printf "  %-12s %s\n" "$@"
}

# 1: unsupported
# 0: supported
declare -i _grep_supports_pcre=
grep_supports_pcre()
{
	if [[ -n "${_grep_supports_pcre}" ]]; then
		return ${_grep_supports_pcre}
	fi

	grep -P xxx < /dev/null 2> /dev/null
	if [[ $? == 2 ]]; then
		_grep_supports_pcre=1
		return 1
	else
		_grep_supports_pcre=0
		return 0
	fi
}

is_available()
{
	type $1 >/dev/null 2>&1
}

foreach_rpmsavenew()
{
	local one_by_one=
	local with_pkg=
	local pkg=

	while [[ $# -gt 0 ]]; do
		case "$1" in
			(-h|--help)
				do_help "${_ACTION}"
				exit 0
				;;
			(--one-by-one)
				one_by_one=1
				shift
				;;
			(--with-pkg)
				with_pkg=1
				shift
				;;
			(--pkg=*)
				pkg=${1#--pkg=}
				shift
				;;
			(-*)
				error "unknown option: $1"
				;;
			(*)
				break
				;;
		esac
	done

	local p f
	local r=0

	local self=$1
	local proc=$2
	shift 2

	local -a opts
	while [[ $# -gt 0 ]]; do
		case "$1" in
			(--)
				shift
				break
				;;
			(*)
				opts+=("$1")
				shift
				;;
		esac
	done

	if [[ $# -eq 0 ]]; then
		while read p f; do
			if [[ -n "$with_pkg" ]]; then
				echo "#"
				echo "# package: $p"
				echo "#"
				echo "---"
			fi

			"$self" "${opts[@]}" "$f" || r=1

			if [[ -n "$with_pkg" ]]; then
				echo
			fi
		done < <(do_list_files --with-pkg --base $pkg)
		return $r
	fi

	for f in "$@"; do
		case "$f" in
			(*.rpmsave)
				f=${f%.rpmsave}
				;;
			(*.rpmnew)
				f=${f%.rpmnew}
				;;
		esac

		if [[ -e "${f}".rpmsave ]]; then
			if [[ -n "${one_by_one}" ]]; then
				$proc "${opts[@]}" "${f}".rpmsave || r=1
				$proc "${opts[@]}" "${f}" || r=1
			else
				$proc "${opts[@]}" "${f}".rpmsave "${f}"
			fi
		elif [[ -e "${f}".rpmnew ]]; then
			if [[ -n "${one_by_one}" ]]; then
				$proc "${opts[@]}" "${f}" || r=1
				$proc "${opts[@]}" "${f}".rpmnew || r=1
			else
				$proc "${opts[@]}" "${f}" "${f}".rpmnew || r=1
			fi
		else
			warning "no rpmnew or rpmsave for ${f}"
		fi
	done
	return $r
}

#
# helpers for writing test cases
#
title()
{
	echo "* $@"
}

tcase()
{
	echo -n "- $@"...
}

ok()
{
	echo "ok"
}

failed()
{
	echo "failed"
	if [[ -n "$@" ]]; then
		cat -n <<< "$@"
	fi
}

#
# action: list-files
#
help_list_files()
{
	echo "  $0 list-files [--with-pkg] [--new|--save|--base|*--both*] [PKG...]"
	echo "  $0 list-files --help|-h"
}

do_list_files()
{
	local filter=both
	local with_pkg=
	local f
	local c

	while [[ $# -gt 0 ]]; do
		case "$1" in
			(-h|--help)
				do_help "${_ACTION}"
				exit 0
				;;
			(--with-pkg)
				with_pkg=1
				shift
				;;
			(--new)
				filter=new
				shift
				;;
			(--save)
				filter=save
				shift
				;;
			(--base)
				filter=base
				shift
				;;
			(--both)
				filter=both
				shift
				;;
			(-*)
				error "unknown option: $1"
				;;
			(*)
				break
				;;
		esac
	done

	local c
	local aflag=

	if [[ $# -eq 0 ]]; then
		aflag=a
	fi

	for f in $(rpm -q${aflag} --configfiles "$@"); do
		# We expect a file name starting with '/'.
		case "$f" in
			(/*) ;;
			(*) continue;;
		esac

		if [[ -e "${f}".rpmsave ]]; then
			case "$filter" in
				(both|save)
					c="${f}.rpmsave"
					;;
				(base)
					c="${f}"
					;;
			esac
		elif [[ -e "${f}".rpmnew ]]; then
			case "$filter" in
				(both|new)
					c="${f}.rpmnew"
					;;
				(base)
					c="${f}"
					;;
			esac
		else
			c=
		fi

		if [[ -n "$c" ]]; then
			if [[ -n "${with_pkg}" ]]; then
				printf "%50s %s\n" $(rpm -qf "$f") "$c"
			else
				printf "%s\n" "$c"
			fi
		fi
	done
}

#
# action: diff
#
help_diff()
{
	echo "  $0 diff [options] [FILE...]"
	echo "  $0 diff [options] --pkg PKG"
	echo "  $0 diff --help|-h"

	options
	print_option --stat "generate diffstat"
	print_option --with-pkg "add package information to the output"
	print_option '--color=auto|always|never' "use markers to highlight the matching strings"
	print_option '--ignore-case' "ignore case differences in file contents"
	print_option '--ignore-tab-expansion' "ignore changes due to tab expansion"
	print_option '--ignore-trailing-space' "ignore white space at line end"
	print_option '--ignore-space-change' "ignore changes in the amount of white space"
	print_option '--ignore-all-space' "ignore all white space"
	print_option '--ignore-blank-lines' "ignore changes where lines are all blank"
	print_option '--ignore-sh-comments' "ignore changes starting from '#'"
}

diff_main()
{
	diff -uN "$@"
}

ignore_sh_comments()
{
	if grep_supports_pcre; then
		grep -P -v $'^(?:\x1b\\[[0-9;]*m)*[-+](?:\x1b\\[[0-9;]*m)*[ \t]*(?:\x1b\\[[0-9;]*m)*#'
	else
		cat
	fi | grep -v $'^[-+][ \t]*#.*$'
}

ignore_blank_lines()
{
	if grep_supports_pcre; then
		grep -P -v $'^(?:\x1b\\[[0-9;]*m)*[-+](?:\x1b\\[[0-9;]*m)*[ \t]*(?:\x1b\\[[0-9;]*m)*$'
	else
		cat
	fi | grep -v $'^[-+][ \t]*$'
}

do_diff()
{
	local f
	local b
	local diffstat
	local with_pkg=
	local color=auto

	local -a ignore
	local ignore_sh_comments=
	local ignore_blank_lines=

	local pkg

	while [[ $# -gt 0 ]]; do
		case "$1" in
			(-h|--help)
				do_help "${_ACTION}"
				exit 0
				;;
			(--stat)
				if ! is_available diffstat; then
					error "Command not available: diffstat"
				fi
				diffstat=1
				shift
				;;
			(--with-pkg)
				with_pkg=$1
				shift
				;;
			(--pkg=*)
				pkg=$1
				shift
				break
				;;
			(--pkg)
				shift
				pkg="--pkg=$1"
				if [[ -z "$pkg" ]]; then
					error "No package given to --pkg option"
				fi
				shift
				break
				;;
			(--color=*)
				color=${1#--color=}
				shift
				;;
			(--color)
				shift
				color=$1
				shift
				;;
			(--ignore-case|--ignore-tab-expansion|--ignore-trailing-space|--ignore-space-change|--ignore-all-space)
				ignore+=("$1")
				shift
				;;
			(--ignore-blank-lines)
				ignore+=("$1")
				ignore_blank_lines=1
				shift
				;;
			(--ignore-sh-comments)
				ignore+=($'--ignore-matching-lines=^[ \t]*#.*')
				ignore_sh_comments=1
				shift
				;;
			(--ignore-matching-lines=*)
				ignore+=("$1")
				shift
				;;
			(-*)
				error "unknown option: $1"
				;;
			(*)
				break
				;;
		esac
	done

	if ! member "$color" auto always never; then
		error "unexpected option argument for --color: $color"
	fi

	if [[ -n "${diffstat}" && "$color" == "always" ]]; then
		error "don't combine --stat and --color=always"
	fi

	if [[ -n "${ignore_sh_comments}" || -n "${ignore_blank_lines}" ]]; then
		if [[ -n "${diffstat}" ]]; then
			if [[ -n "${ignore_sh_comments}" ]]; then
				error "don't combine --stat and --ignore-sh-comments"
			elif [[ -n "${ignore_blank_lines}" ]]; then
				error "don't combine --stat and --ignore-blank-lines"
			fi
		fi
		if ! grep_supports_pcre && [[ "$color" == "always" ]]; then
			if [[ -n "${ignore_sh_comments}" ]]; then
				error "your grep doesn't support -P option; don't combine --color=always and --ignore-sh-comments"
			elif [[ -n "${ignore_blank_lines}" ]]; then
				error "your grep doesn't support -P option; don't combine --color=always and --ignore-blank-lines"
			fi
		fi
		if ! grep_supports_pcre && [[ "$color" == "auto" ]]; then
			color=never
		fi
	fi

	if [[ -n "${diffstat}" ]]; then
		color=never
	elif [[ -t 1 ]]; then
		if [[ "$color" == auto ]]; then
			color=always
		fi
	fi

	{
		foreach_rpmsavenew \
			$with_pkg \
			$pkg \
			"do_${_ACTION//-/_}" "${_ACTION//-/_}"_main \
			--color="$color" \
			"${ignore[@]}" \
			-- "$@"
	} | if [[ -n "${diffstat}" ]]; then
		diffstat
	else
		cat
	fi | if [[ -n "$ignore_sh_comments" ]]; then
		ignore_sh_comments
	else
		cat
	fi | if [[ -n "$ignore_blank_lines" ]]; then
		ignore_blank_lines
	else
		cat
	fi
}

#
# action: sha1
#
help_sha1()
{
	echo "  $0 sha1 [options] [FILE...]"
	echo "  $0 sha1 [options] --pkg PKG"
	echo "  $0 sha1 --help|-h"
	options
	print_option --with-pkg "add package information to the output"
}

sha1_main()
{
	sha1sum "$1"
}

do_sha1()
{
	local f
	local b
	local with_pkg=
	local pkg

	while [[ $# -gt 0 ]]; do
		case "$1" in
			(-h|--help)
				do_help "${_ACTION}"
				exit 0
				;;
			(--with-pkg)
				with_pkg=$1
				shift
				;;
			(--pkg=*)
				pkg=$1
				shift
				break
				;;
			(--pkg)
				shift
				pkg="--pkg=$1"
				if [[ -z "$pkg" ]]; then
					error "No package given to --pkg option"
				fi
				shift
				break
				;;
			(-*)
				error "unknown option: $1"
				;;
			(*)
				break
				;;
		esac
	done

	foreach_rpmsavenew \
		$with_pkg \
		$pkg \
		--one-by-one "do_${_ACTION//-/_}" "${_ACTION//-/_}"_main \
		-- "$@"
}

help_ls_lZ()
{
	echo "  $0 ls-lZ [options] [FILE...]"
	echo "  $0 ls-lZ [options] --pkg PKG"
	echo "  $0 ls-lZ --help|-h"
	options
	print_option --with-pkg "add package information to the output"
}

ls_lZ_main()
{
	ls -lZ "$1"
}

do_ls_lZ()
{
	local with_pkg=
	local f
	local b
	local pkg

	while [[ $# -gt 0 ]]; do
		case "$1" in
			(-h|--help)
				do_help ${_ACTION}
				exit 0
				;;
			(--with-pkg)
				with_pkg=$1
				shift
				;;
			(--pkg=*)
				pkg=$1
				shift
				break
				;;
			(--pkg)
				shift
				pkg="--pkg=$1"
				if [[ -z "$pkg" ]]; then
					error "No package given to --pkg option"
				fi
				shift
				break
				;;
			(-*)
				error "unknown option: $1"
				;;
			(*)
				break
				;;
		esac
	done

	foreach_rpmsavenew \
		$with_pkg \
		$pkg \
		--one-by-one "do_${_ACTION//-/_}" "${_ACTION//-/_}"_main \
		-- "$@"
}

#
# action: archive
#
help_archive()
{
	echo "  $0 archive [--delete-directory] BODYNAME|EXISTING-DIR"
	echo "  $0 archive --help|-h"

	examples

	echo "  # $0 archive /root"
	echo "    => makes /root/rpmsave-PID-TIMESTAMP"
	echo "         and /root/rpmsave-PID-TIMESTAMP.tar"
	echo
	echo "  # $0 archive /root/no-such-dir"
	echo "    => makes /root/no-such-dir"
	echo "         and /root/no-such-dir.tar"
}

copy_out()
{
	local dest=${1#--dest=}
	shift

	cp --parents -ra "$@" "$dest"
}

do_archive_main()
{
	local dest

	while [[ $# -gt 0 ]]; do
		case "$1" in
			(--dest=*)
				dest=$1
				shift
				break
				;;
			(*)
				break;
				;;
		esac
	done

	foreach_rpmsavenew \
		do_archive_main copy_out \
		"$dest" \
		-- "$@"
}

do_archive()
{
	local delete_directory

	while [[ $# -gt 0 ]]; do
		case "$1" in
			(-h|--help)
				do_help "${_ACTION}"
				exit 0
				;;
			(--delete-directory)
				delete_directory=1
				shift
				;;
			(-*)
				error "unknown option: $1"
				;;
			(*)
				break
				;;
		esac
	done

	if [[ $# -eq 0 ]]; then
		error "no archive name or directory given"
	elif [[ $# -gt 1 ]]; then
		error "too many arguments: $@"
	fi

	if ! is_available date; then
		error "command not available: date"
	fi

	local N
	local D
	if [[ -d "$1" ]]; then
		D=$1
		N=$D/rpmsavenew-$$-$(date +'%Y%m%d-%H%M%S')
	else
		N=$1
	fi

	if [[ -z "$N" ]]; then
		error "empty string given as the name of the output target"
	fi

	mkdir -p "$N" || error "fail to do mkdir: $N"

	do_archive_main --dest="$N"
	local s=$?

	if [[ "$s" == 0 ]]; then
		tar cvf "$N".tar "$N"
		s="$?"
	else
		error "error in copy-out operation: $N"
	fi

	if [[ "$s" == 0 && -n "$D" ]]; then
		echo  "$N".tar
	fi

	if [[ "$s" == 0 && -n "$delete_directory" ]]; then
		rm -rf "$N"
	fi

	return $s
}

#
# action: help
#
help_help()
{
	echo "  $0 help [ACTION]"
	echo
	list_actions
}

do_help()
{
	if [[ $# == 0 ]]; then
		show_usage
		exit 0
	fi

	while [[ $# -gt 0 ]]; do
		case "$1" in
			(-h|--help)
				do_help ${_ACTION}
				exit 0
				;;
			(-*)
				error "unknown option: $1"
				;;
			(*)
				break
				;;
		esac
	done

	local a=$1
	if ! member "$a" "${actions[@]}"; then
		error "unknown action: $a"
	fi

	echo "Action usage:"

	a=${a//-/_}
	help_"$a" "$a"
	exit 0
}

#
# action: confspec
#
help_confspec()
{
	echo "  $0 confspec [PKG...]"
	echo "  $0 confspec --help|-h"
}

do_confspec()
{
	local with_pkg
	while [[ $# -gt 0 ]]; do
		case "$1" in
			(-h|--help)
				do_help "${_ACTION}"
				exit 0
				;;
			(--with-pkg)
				with_pkg=$1
				shift
				;;
			(-*)
				error "unknown option: $1"
				;;
			(*)
				break
				;;
		esac
	done

	local p
	local -a pkgs

	if [[ $# -eq 0 ]]; then
		for p in $(rpm -qa); do
			pkgs+=( "$p" )
		done
	else
		for p in "$@"; do
			if ! pkgs+=( $(rpm -q "$p") ) ; then
				error "no such package: $p"
			fi
		done
	fi

	for p in "${pkgs[@]}"; do
		local c

		rpm -q --qf '[%{filenames}: %{fileflags:fflags}\n]' "$p" |
			while read c; do
				case "$c" in
					(*:\ cn)
						if [[ -n "${with_pkg}" ]]; then
							echo "new 	$p	${c%: cn}"
						else
							echo "new 	${c%: cn}"
						fi
						;;
					(*:\ c)
						if [[ -n "${with_pkg}" ]]; then
							echo "save	$p	${c%: c}"
						else
							echo "save	${c%: c}"
						fi
						;;
				esac
			done
	done
}

#
# main
#
list_actions()
{
	local a

	echo "Actions:"
	for a in "${actions[@]}"; do
		echo "  $a"
	done
}

show_usage()
{
	echo "Usage:"
	echo "  $0 -h|--help"
	echo "  $0 help help"
	echo "  $0 ACTION ..."
	echo

	list_actions
}

main()
{
	while [[ $# -gt 0 ]]; do
		case "$1" in
			(-h|--help)
				show_usage
				exit 0
				;;
			(-*)
				error "unknown option: $1"
				;;
			(*)
				break
				;;
		esac
	done

	if [[ $# == 0 ]]; then
		error "no action given"
	fi

	local a=$1
	error_if_unknown_action "$a"
	shift

	_ACTION="$a"
	a=${a//-/_}
	do_"$a" "$@"
}

main "$@"
